import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faUserPlus,
  faCalendarCheck,
  faUser,
  faHouse,
  faChevronLeft,
  faDownload,
  faUserDoctor,
  faArrowRightFromBracket,
  faUserCheck,
  faPills,
  faList,
  faSquareCheck,
  faSquareXmark,
  faHospitalUser,
  faTrashCan,
  faSquarePlus,
  faFloppyDisk,
  faMagnifyingGlass,
  faEye,
  faEyeSlash,
  faPenToSquare,
  faXmark,
  faFilePrescription,
  faChartLine,
} from "@fortawesome/free-solid-svg-icons";
import { MdEmergency } from "react-icons/md";
import { FaAmbulance } from "react-icons/fa";

const Shared = {
  UserPlus: <FontAwesomeIcon icon={faUserPlus} />,
  calendarCheck: <FontAwesomeIcon icon={faCalendarCheck} />,
  User: <FontAwesomeIcon icon={faUser} />,
  HomeUser: <FontAwesomeIcon icon={faHouse} />,
  Prescription: <FontAwesomeIcon icon={faFilePrescription} />,
  ArrowLeft: <FontAwesomeIcon icon={faChevronLeft} />,
  Download: <FontAwesomeIcon icon={faDownload} />,
  DoctorHome: <FontAwesomeIcon icon={faUserDoctor} />,
  LogOut: <FontAwesomeIcon icon={faArrowRightFromBracket} />,
  DoctorCheckin: <FontAwesomeIcon icon={faUserCheck} />,
  Pills: <FontAwesomeIcon icon={faPills} />,
  List: <FontAwesomeIcon icon={faList} />,
  SquareCheck: <FontAwesomeIcon icon={faSquareCheck} />,
  SquareCross: <FontAwesomeIcon icon={faSquareXmark} />,
  Report: <FontAwesomeIcon icon={faHospitalUser} />,
  Emergency: <MdEmergency />,
  Ambulance: <FaAmbulance />,
  TrashCan: <FontAwesomeIcon icon={faTrashCan} />,
  SquarePlus: <FontAwesomeIcon icon={faSquarePlus} />,
  Save: <FontAwesomeIcon icon={faFloppyDisk} />,
  Search: <FontAwesomeIcon icon={faMagnifyingGlass} />,
  Eye: <FontAwesomeIcon icon={faEye} />,
  SlashEye: <FontAwesomeIcon icon={faEyeSlash} />,
  Edit: <FontAwesomeIcon icon={faPenToSquare} />,
  Cancel: <FontAwesomeIcon icon={faXmark} />,
  Anaytics: <FontAwesomeIcon icon={faChartLine} />,
};

export default Shared;
